analytics:
  provider: google-gtag
  google:
    tracking_id: G-4GWDNRQLN1
author:
  name: Jesús Leganés-Combarro ‘piranna’
  avatar: https://avatars0.githubusercontent.com/u/532414
  bio: |
    Passionate computers engineer and ex-PhD. candidate in Computers
    Engineering. Proud advocate of Open Source, standards, specifications, and
    best practices.
  location: Madrid, Spain / Abu Dhabi, UAE
  links:
    - label: Personal web page
      icon: "fas fa-fw fa-link"
      url: https://piranna.github.io
    - label: GitHub
      icon: "fab fa-fw fa-github"
      url: https://github.com/piranna
    - label: Twitter
      icon: "fab fa-fw fa-twitter-square"
      url: https://twitter.com/el_piranna
breadcrumbs: true
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      layout: single
      read_time: true
      show_date: true
description: |
  Massively parallel vertical and horizontal scalable SFU (Stream Forwarding
  Unit) built on top of Mediasoup
facebook:
  publisher: 100089773552926
footer:
  links:
    - label: Twitter
      icon: fab fa-fw fa-twitter-square
      url: https://twitter.com/mafalda_sfu
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/mafalda-sfu
    - label: NPM
      icon: fab fa-fw fa-npm
      url: https://npmjs.com/org/mafalda-sfu
    - label: Legal
      icon: fas fa-fw fa-balance-scale
      url: /legal/
include: [_pages]
jekyll-spaceship:
  mermaid-processor:
    mode: pre-fetch  # fetch image at building stage
    syntax:
      code: mermaid
logo: &logo /assets/images/logo.png
lunr:
  search_full_content: true
  search_within_pages: true
minimal_mistakes_skin: sunrise
name: Jesús Leganés-Combarro 'piranna'
og_image: *logo
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-spaceship
remote_theme: mmistakes/minimal-mistakes@4.24.0
# https://talk.jekyllrb.com/t/error-your-site-could-not-be-built-no-repo-name-found/5688/3
repository: Mafalda-SFU/Mafalda-SFU.github.io
search: true
title: Mafalda SFU
twitter:
  username: mafalda_sfu
url: https://mafalda.io
